### PR TITLE
Bearing/heading

### PR DESCRIPTION
**Pull request by jorix**
Hello Xavier,

I have slightly modified your code as I needed not only distance but bearing as well. I can share the patch if you'd like to investigate/include.

Thanks for the module, it saved me lot of time.

Cheers

### CODE REVIEW

**Comment by jorix** [comment]
@aberenyi 

Thanks for the code, I still have work to do.

**Comment by aberenyi** [comment]
@jorix 

Cheers!

**Comment by jorix** [comment]
Hi @aberenyi I think it's finished. 

The default options are different from those that you proposed. To customize how your proposal should use this:

``` javascript
var control = new OpenLayers.Control.DynamicMeasure(OpenLayers.Handler.Path, {
    layerHeadingOptions:{},  // to show headings (default us null, don't show)
    maxHeadings: null, // to show more that last heading (deafult is 1)
    positions: { // to change default positions for segments lengths and headings
        labelSegments: 'end',
        labelHeading: 'middle'
    }
});
```

**Pull request merged**
