### PR TITLE
Persistent annotations

### PR DESCRIPTION
**Pull request by jdenisgiguere**
## Summary

DynamicMeasure  allows us to store geometry of measured feature which is great!

In this pull request, we offer the possibility of storing annotations (segment, length and area) in  persistent layer which will stay available during the next measurements. The persistent annotations will even stay available after deactivation. They will be removed by calling a method on DynamicMeasure control.
### API modification
- `keep` : Property {Boolean} - keep annotations for every measures
- `emptyKeeped()` :  Method - empty keeped annotations;
- `layerSegmentsKeep`, `layerLengthKeep`, `layerAreaKeep` : Property  {`<OpenLayers.Layer.Vector>`} layers to keep copy of annotations;
### Code modifications

Several methods are affected by the proposed modification.

The method `copyAnnotations` makes most of the work.

### CODE REVIEW

**Comment by jorix** [comment]
This has a very good look!

Later I I test a little and merge.

Thanks for cooperating!

**Comment by jorix** [comment]
There seems exist a little bug:
- draw a line
- press `Empty keeped annotations!`
- draw another line
- start drawing the third, opp! Previous total length to us persecutes us. 
- add a point, opp! The second line is not completed.

**Comment by jdenisgiguere** [comment]
Thank you @jorix  for the test case.

Any further comments are welcome.

**Comment by jorix** [comment]
@jdenisgiguere : Only last two comments:
- On `destroy` seems better destroy the layers layerXxxxxKeep and set to null.
- Add link to example on README

... and thanks!

**Comment by jdenisgiguere** [comment]
@jorix : I think commit 12d50d6 resolves pending issues. Do you have further comments ?

Kind regards,

**Comment by jorix** [comment]
@jdenisgiguere  Thanks!!

See my 1d40ecc528b9db90c13020c5d1c7418720e43d04 after merge. Docs are updated.

**Comment by jorix** [comment]
... and see fec275829c0b1c59a117dd1b7036f4e354cad8b4

**Pull request merged**
